'''
Created on 21/04/2013

@author: gustavo
'''

class Error_Status:
    NONE = 0X0
    INPUT_VOLTAGE = 0X1
    ANGLE_LIMIT = 0X2
    OVERHEATING = 0X4
    RANGE = 0X8
    CHECKSUM = 0X10
    OVERLOAD = 0X20
    INSTRUCTION = 0X40

class Register:
    MODEL_NUMBER = 0
    FIRMWARE_VERSION = 2
    ID = 3
    BAUD_RATE = 4
    RETURN_DELAY = 5
    CW_ANGLE_LIMIT = 6
    CCW_ANGLE_LIMIT = 8
    TEMPERATURE_LIMIT = 11
    LOW_VOLTAGE_LIMIT = 12
    HIGH_VOLTAGE_LIMIT = 13
    MAX_TORQUE = 14
    STATUS_RETURN_LEVEL = 16
    ALARM_LED = 17
    ALARM_SHUTDOWN = 18
    DOWN_CALIBRATION = 20
    UP_CALIBRATION = 22
    TORQUE_ENABLE = 24
    LED = 25
    CW_COMPILANCE_MARGIN = 26
    CCW_COMPILANDE_MARGIN = 27
    CW_COMPILANCE_SLOPE = 28
    CCW_COMPILANDE_SLOPE = 29
    GOAL_POSITION = 30
    MOVING_SPEED = 32
    TORQUE_LIMIT = 34
    CURRENT_POSITION = 36
    CURRENT_SPEED = 38
    CURRENT_LOAD = 40
    CURRENT_VOLTAGE = 42
    CURRENT_TEMPERATURE = 43
    REGISTERED_INSTRUCTION = 44
    MOVING = 46
    LOCK = 47
    PUNCH = 48

class Status_Return_Level:
    NO_RESPONSE = 0
    RESPOND_TO_READ_DATA = 1
    RESPOND_ALL = 2

class Instruction:
    PING = 1
    READ_DATA = 2
    WRITE_DATA = 3
    REG_WRITE = 4
    ACTION = 5
    RESET = 6
    SYNC_READ = 0X82
    SYNC_WRITE = 0X83


# Fin
